# Generated by Django 2.0 on 2018-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cart_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
