# Generated by Django 2.0.7 on 2018-11-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_restrictedipdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictedipdevice',
            name='who_did',
            field=models.CharField(blank=True, help_text='Determines who added this User or Admin', max_length=250, null=True),
        ),
    ]
