# Generated by Django 2.0.7 on 2018-09-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, help_text='Company name, acts as key', max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, help_text='Name of the company', max_length=150, null=True)),
                ('last_sale', models.CharField(blank=True, default=False, max_length=100)),
                ('market_cap', models.CharField(blank=True, default=False, max_length=100)),
                ('adr_tso', models.CharField(blank=True, default=False, max_length=100)),
                ('ipo_year', models.CharField(blank=True, default=False, max_length=100)),
                ('sector', models.CharField(blank=True, default=False, max_length=100)),
                ('industry', models.TextField(blank=True, default=False)),
                ('status', models.BooleanField(default=True)),
                ('coming_soon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(blank=True)),
                ('high', models.CharField(blank=True, default=False, max_length=100)),
                ('low', models.CharField(blank=True, default=False, max_length=100)),
                ('close', models.CharField(blank=True, default=False, max_length=100)),
                ('accuracy_prev_day', models.CharField(blank=True, default='N.A.', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockprediction',
            unique_together={('stock', 'prediction_date')},
        ),
    ]
